# Data to contribute to UP Repo

In [42]:
# Enable Intellisense
%config IPCompleter.greedy=True

import pandas as pd
import numpy as np
import io
import requests
import seaborn as sns
from matplotlib import pyplot, dates
import plotly.express as px 
import datetime
import plotly.graph_objects as go
import plotly.io as pio
sns.set()

from datetime import datetime

# Annoying warning
pd.options.mode.chained_assignment = None  # default='warn'

## Gen Helper Functions

In [5]:
def df_from_url(df_url, pd_kwargs={}):
    df_req = requests.get(df_url).content
    df = pd.read_csv(io.StringIO(df_req.decode('utf-8')), **pd_kwargs)
    return df

In [15]:
prov_dict = {
    "Eastern Cape":"EC",
    "Free State":"FS",
    "Gauteng":"GP",
    "KwaZulu-Natal":"KZN",
    "Limpopo":"LP",
    "Mpumalanga":"MP",
    "Northern Cape":"NC",
    "North West":"NW",
    "Western Cape":"WC",
    "Unknown":"UNKNOWN"
}

In [28]:
def change_date_format(in_date):
    return in_date.strftime('%Y%m%d')

## Deaths Per Prov

In [11]:
orig_data = df_from_url("https://raw.githubusercontent.com/dsfsi/covid19za/master/data/" + 
                        "covid19za_provincial_cumulative_timeline_deaths.csv", )
orig_data

          date  YYYYMMDD  EC  FS  GP  KZN  LP  MP  NC  NW  WC  UNKNOWN  total
0   27-03-2020  20200327   0   0   0    0   0   0   0   0   1        0      1
1   28-03-2020  20200328   0   0   0    1   0   0   0   0   1        0      2
2   30-03-2020  20200330   0   1   0    1   0   0   0   0   1        0      3
3   31-03-2020  20200331   0   1   1    2   0   0   0   0   1        0      5
4   03-04-2020  20200403   0   1   1    6   0   0   0   0   1        0      9
5   05-04-2020  20200405   0   1   1    7   0   0   0   0   2        0     11
6   06-04-2020  20200406   0   1   1    7   0   0   0   0   3        0     12
7   07-04-2020  20200407   0   1   1    8   0   0   0   0   3        0     13
8   08-04-2020  20200408   0   3   3    9   0   0   0   0   3        0     18
9   09-04-2020  20200409   0   3   3    9   0   0   0   0   3        0     18
10  10-04-2020  20200410   0   3   3   12   0   0   0   0   6        0     24
11  11-04-2020  20200411   0   3   3   12   0   0   0   0   7        0     25
12  12-04-2020  20200412   0   3   3   12   0   0   0   0   7        0     25
13  13-04-2020  20200413   0   3   4   12   0   0   0   0   8        0     27
14  14-04-2020  20200414   0   3   4   12   0   0   0   0   8        0     27
15  15-04-2020  20200415   0   3   5   18   0   0   0   0   8        0     34
16  16-04-2020  20200416   4   4   6   20   1   0   0   0  13        0     48
17  17-04-2020  20200417   4   4   6   20   1   0   0   0  15        0     50
18  18-04-2020  20200418   4   4   6   21   1   0   0   0  16        0     52
19  19-04-2020  20200419   4   4   6   22   1   0   0   0  17        0     54
20  20-04-2020  20200420   5   5   7   23   1   0   0   0  17        0     58
21  21-04-2020  20200421   5   5   7   23   1   0   0   0  17        0     58
22  22-04-2020  20200422   5   5   7   25   1   0   0   0  22        0     65
23  23-04-2020  20200423   6   5   8   27   1   0   0   0  28        0     75
24  24-04-2020  20200424   6   5   8   29   1   0   0   0  30        0     79
25  25-04-2020  20200425  10   5   8   29   2   0   0   0  32        0     86
26  26-04-2020  20200426  10   5   8   29   2   0   0   0  33        0     87
27  27-04-2020  20200427  10   5   8   30   2   0   0   0  35        0     90
28  28-04-2020  20200428  10   5   8   30   2   0   0   0  38        0     93
29  29-04-2020  20200429  11   5  11   32   2   0   0   0  42        0    103
30  30-04-2020  20200430  11   5  11   32   2   0   0   0  42        0    103

In [52]:
# Do some pre-processing before add
def add_to_data(orig_data, add_data, date):
    _add_data = add_data.copy() # Might be unneccesary but I'm not sure if add_data is passed by reference
    _add_data['date'] = date
    _add_data['date'] = pd.to_datetime(_add_data['date'], format='%d-%m-%Y')
    _add_data['province'] = add_data['province'].map(prov_dict)
    
    add_data_piv = _add_data.pivot(index='date', columns='province', values=['tot_deaths'])

    add_data_piv.columns = add_data_piv.columns.droplevel(level=0)
    add_data_piv.columns.name = ""
    add_data_piv.reset_index(inplace = True)

    add_data_piv['total'] = add_data_piv.drop(['date'], axis=1).sum(axis=1)
    add_data_piv['YYYYMMDD'] = add_data_piv['date'].apply(change_date_format)
#     print(type(add_data_piv['date'].iloc[-1]))
    add_data_piv['date'] = add_data_piv['date'].apply(lambda x: x.to_pydatetime().strftime("%d-%m-%Y"))

    new_data = pd.concat([orig_data, add_data_piv], axis = 0)
    return new_data

In [54]:
add_data = pd.read_csv('data/tot_deaths_provinces_01.csv')
new_data = add_to_data(orig_data, add_data, '01-05-2020')
new_data

          date  YYYYMMDD  EC  FS  GP  KZN  LP  MP  NC  NW  WC  UNKNOWN  total
0   27-03-2020  20200327   0   0   0    0   0   0   0   0   1        0      1
1   28-03-2020  20200328   0   0   0    1   0   0   0   0   1        0      2
2   30-03-2020  20200330   0   1   0    1   0   0   0   0   1        0      3
3   31-03-2020  20200331   0   1   1    2   0   0   0   0   1        0      5
4   03-04-2020  20200403   0   1   1    6   0   0   0   0   1        0      9
5   05-04-2020  20200405   0   1   1    7   0   0   0   0   2        0     11
6   06-04-2020  20200406   0   1   1    7   0   0   0   0   3        0     12
7   07-04-2020  20200407   0   1   1    8   0   0   0   0   3        0     13
8   08-04-2020  20200408   0   3   3    9   0   0   0   0   3        0     18
9   09-04-2020  20200409   0   3   3    9   0   0   0   0   3        0     18
10  10-04-2020  20200410   0   3   3   12   0   0   0   0   6        0     24
11  11-04-2020  20200411   0   3   3   12   0   0   0   0   7        0     25
12  12-04-2020  20200412   0   3   3   12   0   0   0   0   7        0     25
13  13-04-2020  20200413   0   3   4   12   0   0   0   0   8        0     27
14  14-04-2020  20200414   0   3   4   12   0   0   0   0   8        0     27
15  15-04-2020  20200415   0   3   5   18   0   0   0   0   8        0     34
16  16-04-2020  20200416   4   4   6   20   1   0   0   0  13        0     48
17  17-04-2020  20200417   4   4   6   20   1   0   0   0  15        0     50
18  18-04-2020  20200418   4   4   6   21   1   0   0   0  16        0     52
19  19-04-2020  20200419   4   4   6   22   1   0   0   0  17        0     54
20  20-04-2020  20200420   5   5   7   23   1   0   0   0  17        0     58
21  21-04-2020  20200421   5   5   7   23   1   0   0   0  17        0     58
22  22-04-2020  20200422   5   5   7   25   1   0   0   0  22        0     65
23  23-04-2020  20200423   6   5   8   27   1   0   0   0  28        0     75
24  24-04-2020  20200424   6   5   8   29   1   0   0   0  30        0     79
25  25-04-2020  20200425  10   5   8   29   2   0   0   0  32        0     86
26  26-04-2020  20200426  10   5   8   29   2   0   0   0  33        0     87
27  27-04-2020  20200427  10   5   8   30   2   0   0   0  35        0     90
28  28-04-2020  20200428  10   5   8   30   2   0   0   0  38        0     93
29  29-04-2020  20200429  11   5  11   32   2   0   0   0  42        0    103
30  30-04-2020  20200430  11   5  11   32   2   0   0   0  42        0    103
0   01-05-2020  20200501  11   5  11   32   2   0   0   0  55        0    116

In [55]:
add_data = pd.read_csv('data/tot_deaths_provinces_02.csv')
new_data = add_to_data(new_data, add_data, '02-05-2020')
new_data

          date  YYYYMMDD  EC  FS  GP  KZN  LP  MP  NC  NW  WC  UNKNOWN  total
0   27-03-2020  20200327   0   0   0    0   0   0   0   0   1        0      1
1   28-03-2020  20200328   0   0   0    1   0   0   0   0   1        0      2
2   30-03-2020  20200330   0   1   0    1   0   0   0   0   1        0      3
3   31-03-2020  20200331   0   1   1    2   0   0   0   0   1        0      5
4   03-04-2020  20200403   0   1   1    6   0   0   0   0   1        0      9
5   05-04-2020  20200405   0   1   1    7   0   0   0   0   2        0     11
6   06-04-2020  20200406   0   1   1    7   0   0   0   0   3        0     12
7   07-04-2020  20200407   0   1   1    8   0   0   0   0   3        0     13
8   08-04-2020  20200408   0   3   3    9   0   0   0   0   3        0     18
9   09-04-2020  20200409   0   3   3    9   0   0   0   0   3        0     18
10  10-04-2020  20200410   0   3   3   12   0   0   0   0   6        0     24
11  11-04-2020  20200411   0   3   3   12   0   0   0   0   7        0     25
12  12-04-2020  20200412   0   3   3   12   0   0   0   0   7        0     25
13  13-04-2020  20200413   0   3   4   12   0   0   0   0   8        0     27
14  14-04-2020  20200414   0   3   4   12   0   0   0   0   8        0     27
15  15-04-2020  20200415   0   3   5   18   0   0   0   0   8        0     34
16  16-04-2020  20200416   4   4   6   20   1   0   0   0  13        0     48
17  17-04-2020  20200417   4   4   6   20   1   0   0   0  15        0     50
18  18-04-2020  20200418   4   4   6   21   1   0   0   0  16        0     52
19  19-04-2020  20200419   4   4   6   22   1   0   0   0  17        0     54
20  20-04-2020  20200420   5   5   7   23   1   0   0   0  17        0     58
21  21-04-2020  20200421   5   5   7   23   1   0   0   0  17        0     58
22  22-04-2020  20200422   5   5   7   25   1   0   0   0  22        0     65
23  23-04-2020  20200423   6   5   8   27   1   0   0   0  28        0     75
24  24-04-2020  20200424   6   5   8   29   1   0   0   0  30        0     79
25  25-04-2020  20200425  10   5   8   29   2   0   0   0  32        0     86
26  26-04-2020  20200426  10   5   8   29   2   0   0   0  33        0     87
27  27-04-2020  20200427  10   5   8   30   2   0   0   0  35        0     90
28  28-04-2020  20200428  10   5   8   30   2   0   0   0  38        0     93
29  29-04-2020  20200429  11   5  11   32   2   0   0   0  42        0    103
30  30-04-2020  20200430  11   5  11   32   2   0   0   0  42        0    103
0   01-05-2020  20200501  11   5  11   32   2   0   0   0  55        0    116
0   02-05-2020  20200502  13   6  12   34   2   0   0   0  56        0    123

In [56]:
new_data.to_csv('covid19za_provincial_cumulative_timeline_deaths.csv', index=False)

In [57]:
pd.read_csv('covid19za_provincial_cumulative_timeline_deaths.csv')

          date  YYYYMMDD  EC  FS  GP  KZN  LP  MP  NC  NW  WC  UNKNOWN  total
0   27-03-2020  20200327   0   0   0    0   0   0   0   0   1        0      1
1   28-03-2020  20200328   0   0   0    1   0   0   0   0   1        0      2
2   30-03-2020  20200330   0   1   0    1   0   0   0   0   1        0      3
3   31-03-2020  20200331   0   1   1    2   0   0   0   0   1        0      5
4   03-04-2020  20200403   0   1   1    6   0   0   0   0   1        0      9
5   05-04-2020  20200405   0   1   1    7   0   0   0   0   2        0     11
6   06-04-2020  20200406   0   1   1    7   0   0   0   0   3        0     12
7   07-04-2020  20200407   0   1   1    8   0   0   0   0   3        0     13
8   08-04-2020  20200408   0   3   3    9   0   0   0   0   3        0     18
9   09-04-2020  20200409   0   3   3    9   0   0   0   0   3        0     18
10  10-04-2020  20200410   0   3   3   12   0   0   0   0   6        0     24
11  11-04-2020  20200411   0   3   3   12   0   0   0   0   7        0     25
12  12-04-2020  20200412   0   3   3   12   0   0   0   0   7        0     25
13  13-04-2020  20200413   0   3   4   12   0   0   0   0   8        0     27
14  14-04-2020  20200414   0   3   4   12   0   0   0   0   8        0     27
15  15-04-2020  20200415   0   3   5   18   0   0   0   0   8        0     34
16  16-04-2020  20200416   4   4   6   20   1   0   0   0  13        0     48
17  17-04-2020  20200417   4   4   6   20   1   0   0   0  15        0     50
18  18-04-2020  20200418   4   4   6   21   1   0   0   0  16        0     52
19  19-04-2020  20200419   4   4   6   22   1   0   0   0  17        0     54
20  20-04-2020  20200420   5   5   7   23   1   0   0   0  17        0     58
21  21-04-2020  20200421   5   5   7   23   1   0   0   0  17        0     58
22  22-04-2020  20200422   5   5   7   25   1   0   0   0  22        0     65
23  23-04-2020  20200423   6   5   8   27   1   0   0   0  28        0     75
24  24-04-2020  20200424   6   5   8   29   1   0   0   0  30        0     79
25  25-04-2020  20200425  10   5   8   29   2   0   0   0  32        0     86
26  26-04-2020  20200426  10   5   8   29   2   0   0   0  33        0     87
27  27-04-2020  20200427  10   5   8   30   2   0   0   0  35        0     90
28  28-04-2020  20200428  10   5   8   30   2   0   0   0  38        0     93
29  29-04-2020  20200429  11   5  11   32   2   0   0   0  42        0    103
30  30-04-2020  20200430  11   5  11   32   2   0   0   0  42        0    103
31  01-05-2020  20200501  11   5  11   32   2   0   0   0  55        0    116
32  02-05-2020  20200502  13   6  12   34   2   0   0   0  56        0    123

In [51]:
type(new_data['date'].iloc[-1])

pandas._libs.tslibs.timestamps.Timestamp

In [43]:
datetime.now().strftime("%d-%m-%Y")

'03-05-2020'